# Generated by Django 4.0.6 on 2022-07-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название задачи')),
                ('content', models.TextField(blank=True, verbose_name='Контент')),
                ('date_added', models.DateTimeField(auto_now=True, verbose_name='Время добавления')),
                ('date_closed', models.DateTimeField(verbose_name='Время завершения')),
                ('status', models.CharField(choices=[('not_active', 'Не активно'), ('active', 'Активно'), ('in_process', 'В процессе'), ('done', 'Завершено')], default='active', max_length=50, verbose_name='Статус')),
            ],
        ),
    ]
